services:
  - type: web
    name: aria-blaze-bot
    env: python
    pythonVersion: "3.11"
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
